local state = require "_scripts/MiniGame.Game_State"
go.property("speed", 300)
local TARGET_GROUPS = {
	[hash("Tree")] = true,
	[hash("Rock")] = true,
	[hash("FinishLine")] = true,
	[hash("Coin")] = true
}

function update(self, dt)
	if not state.active then
		return
	end
	local p = go.get_position()
	p.y = p.y + (self.speed * dt)
	go.set_position(p)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_speed") then
		self.speed = message.speed
	elseif message_id == hash("force_despawn") then
		go.delete()
	end
	if message_id == hash("trigger_response") and message.enter then
		local other_group = message.other_group

		if other_group == hash("Player") or
			other_group == hash("Map") then
			go.delete()
		elseif TARGET_GROUPS[other_group] then
			if go.get_id() > message.other_id then
				go.delete()
			end
		end
	end
end

function final(self)
	-- Quando l'oggetto viene rimosso per qualsiasi motivo (colpito o uscito dallo schermo)
	msg.post("/spawner#ObstacleSpawner", "remove_from_list", { id = go.get_id() })
end