go.property("speed", 300) -- Velocità di scorrimento
local WINDOW_HEIGHT = tonumber(sys.get_config("display.height"))
local state = require "_scripts/MiniGame.Game_State"

function update(self, dt)
	if not state.active then
		return
	end
	local p = go.get_position()
	-- Muove l'oggetto verso il basso
	p.y = p.y + (self.speed * dt)
	go.set_position(p)
end

function on_message(self, message_id, message, sender)
	-- Controlla se il messaggio riguarda l'ingresso in un trigger
	if message_id == hash("trigger_response") and message.enter then
		-- message.other_id è l'id dell'oggetto colpito (es. il player)
		print("Collisione con: " .. message.other_id)

		-- Elimina l'ostacolo immediatamente
		go.delete()
	end
end