local state = require "_scripts/MiniGame.Game_State"
local lanes = {}
local last_lane = 0
for i=1,25 do
	lanes[i] = i * 30
end

local TYPES = {
	{ id = "#tree_Factory", weight = 30 },
	{ id = "#rock_Factory", weight = 30 },
	{ id = "#coin_Factory", weight = 30 },
	{ id = "#finish_Factory", weight = 10 }
}

local function get_weighted_type()
	local total_weight = 0
	for _, t in ipairs(TYPES) do total_weight = total_weight + t.weight end
	local roll = math.random(1, total_weight)
	local current = 0
	for _, t in ipairs(TYPES) do
		current = current + t.weight
		if roll <= current then return t.id end
	end
end

local function spawn_obstacle(self)
	local current_lane = lanes[math.random(1, #lanes)]

	while current_lane == (last_lane + 40) or 
	current_lane == (last_lane - 40) or
	current_lane == last_lane do
		current_lane = lanes[math.random(1, #lanes)]
	end
	last_lane = current_lane

	local pos = vmath.vector3(current_lane, -50, 0.1)
	local obstacle = get_weighted_type()

	factory.create(obstacle, pos)
end

local function aumenta_difficolta(self)
	if not state.active then 
		return
	end	

	if self.spawn_interval == 0.3 then
		for i = 1, 4 do
			spawn_obstacle()
		end
	end

	self.spawn_interval = self.spawn_interval - 0.05

	if self.spawn_interval < 0.3 then
		self.spawn_interval = 0.3
	end

	timer.cancel(self.spawn_timer_handle)
	self.spawn_timer_handle = timer.delay(self.spawn_interval, true, spawn_obstacle)
end

function init(self)
	state.active = true
	math.randomseed(os.time())
	self.spawn_interval = 1.0
	self.spawn_timer_handle = timer.delay(self.spawn_interval, true, spawn_obstacle)

	self.diff_timer_handle = timer.delay(1, true, aumenta_difficolta) -- NON SO A COSA SERVA (perché 1 secondo?)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("stop_spawning") then
		if self.spawn_timer_handle then
			timer.cancel(self.spawn_timer_handle)
			self.spawn_timer_handle = nil
		end

		if self.diff_timer_handle then
			timer.cancel(self.diff_timer_handle)
			self.diff_timer_handle = nil
		end
	end
end