local data = require "_scripts.GameManager" -- Replace with your actual file name

function update(self, dt)
	-- Update Money node
	local money_node = gui.get_node("money_text")
	gui.set_text(money_node, "Cash: $" .. data.money_amount)

	-- Update Knowledge node
	local info_node = gui.get_node("knowledge_text")
	gui.set_text(info_node, "Brain: " .. data.knowledge_amount)

	-- Update Hunger node
	local hunger_node = gui.get_node("hunger_text")
	gui.set_text(hunger_node, "Hunger: " .. math.ceil(data.hunger_amount) .. "%")
end