local GameManager = require("_scripts.GameManager")

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#MainMenu", "load")
	GameManager.set_current_level("MainMenu")
end

local function switch_to_level(self, current_level, next_level)
	msg.post("#" .. current_level, "unload")
	msg.post("#" .. next_level, "load")
	GameManager.set_current_level(next_level)
end	

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "enable")
		if self.pending_end_message then
			msg.post("Menu:/Gui#Menu", "show_end_menu", self.pending_end_message)
			self.pending_end_message = nil
		end
	end

	if message_id == hash("change_level") then
		local current = GameManager.get_current_level()
		local next_level = message.target -- Legge il target inviato dallo yeti

		-- Se il target esiste ed è diverso dal livello attuale, cambia 
		if next_level and next_level ~= current then
			switch_to_level(self, current, next_level)
		end
	elseif message_id == hash("show_end_menu") then
		self.pending_end_message = {
			coins = message.coins,
			reason = message.reason
		}
		switch_to_level(self, "MiniGame", "MiniGameMenu")
	end
end
