embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"background\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/MiniGameMap.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "endSlope"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"Map\"\n"
  "mask: \"Tree\"\n"
  "mask: \"Rock\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 190.74158\n"
  "      z: 1.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"hitbox\"\n"
  "  }\n"
  "  data: 382.0533\n"
  "  data: 128.66138\n"
  "  data: 40.232\n"
  "}\n"
  ""
}
