local speed = 300

function init(self)
	msg.post(".", "acquire_input_focus")
	self.dir = vmath.vector3()
	self.current_anim = nil
	self.correction = vmath.vector3()

	local width = tonumber(sys.get_config("display.width"))
	local height = tonumber(sys.get_config("display.height"))
	self.window_width = width
	self.window_height = height

	local shape_props = physics.get_shape("#yeti_collisionobject", "yeti_hitbox")
	self.margin_x = shape_props.dimensions.x / 2
	self.margin_y = shape_props.dimensions.y / 2
end

function update(self, dt)
	self.correction = vmath.vector3()

	local move_dir = vmath.vector3(self.dir.x, self.dir.y, 0)
	if vmath.length_sqr(move_dir) > 1 then
		move_dir = vmath.normalize(move_dir)
	end

	local p = go.get_position()
	local new_p = p + move_dir * speed * dt

	new_p.x = math.max(self.margin_x, math.min(new_p.x, self.window_width - self.margin_x))
	new_p.y = math.max(self.margin_y, math.min(new_p.y, self.window_height - self.margin_y))

	go.set_position(new_p)

	local anim = self.current_anim or hash("front")
	if move_dir.x > 0 then anim = hash("right")
	elseif move_dir.x < 0 then anim = hash("left")
	elseif move_dir.y > 0 then anim = hash("back")
	elseif move_dir.y < 0 then anim = hash("front")
	end

	if anim ~= self.current_anim then
		sprite.play_flipbook("#sprite", anim)
		self.current_anim = anim
	end

	local pos = go.get_position()
	pos.z = 1 - (pos.y / 10000)
	go.set_position(pos)
end

local function update_direction(self, axis, value, is_pressed)
	if is_pressed then
		self.dir[axis] = value
	elseif self.dir[axis] == value then
		self.dir[axis] = 0
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") and message.other_group == hash("map") then
		msg.post("main:/SceneParent#Main", "change_level", { target = "StartPage"})
	end

	if message_id == hash("contact_point_response") then
		if message.group == hash("environment") and message.distance > 0 then
			local proj = vmath.project(self.correction, message.normal * message.distance)
			if proj < 1 then
				local comp = (message.distance - message.distance * proj) * message.normal
				go.set_position(go.get_position() + comp)
				self.correction = self.correction + comp
			end
		end
	end
end

function on_input(self, action_id, action)
	local is_pressed = not action.released
	if action_id == hash("up") then update_direction(self, "y", 1, is_pressed)
	elseif action_id == hash("down") then update_direction(self, "y", -1, is_pressed)
	elseif action_id == hash("left") then update_direction(self, "x", -1, is_pressed)
	elseif action_id == hash("right") then update_direction(self, "x", 1, is_pressed)
	end
end