components {
  id: "yeti"
  component: "/main/player/yeti.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"back\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/yeti.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "yeti_collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"yeti\"\n"
  "mask: \"houses\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"yeti_hitbox\"\n"
  "  }\n"
  "  data: 38.3046\n"
  "  data: 54.563282\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
