local speed = 300
local GameManager = require("_scripts.GameManager")
local current_level_name
local WINDOW_WIDTH = tonumber(sys.get_config("display.width"))
local WINDOW_HEIGHT = tonumber(sys.get_config("display.height"))

function init(self)
	msg.post(".", "acquire_input_focus")
	current_level_name = GameManager.get_current_level()
	self.dir = vmath.vector3()
	self.current_anim = nil
	pprint("height: ".. WINDOW_HEIGHT)
	pprint("width: " .. WINDOW_WIDTH)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	if vmath.length_sqr(self.dir) > 0 then
		self.dir = vmath.normalize(self.dir)
	end
	local p = go.get_position()
	local new_p = p + self.dir * speed * dt

	local shape_props = physics.get_shape("#yeti_collisionobject", "yeti_hitbox")
	local margin_x = shape_props.dimensions.x / 2
	local margin_y = shape_props.dimensions.y / 2

	if new_p.x < margin_x then
		new_p.x = margin_x
	elseif new_p.x > (WINDOW_WIDTH - margin_x) then
		new_p.x = WINDOW_WIDTH - margin_x
	end

	if new_p.y < margin_y then
		new_p.y = margin_y
	elseif new_p.y > (WINDOW_HEIGHT - margin_y) then
		new_p.y = WINDOW_HEIGHT - margin_y
	end
	--pprint("new pos " .. new_p)
	go.set_position(new_p)

	local anim = hash("front")
	if self.dir.x > 0 then anim = hash("right")
	elseif self.dir.x < 0 then anim = hash("left")
	elseif self.dir.y > 0 then anim = hash("back")
	elseif self.dir.y < 0 then anim = hash("front")
	end

	if anim ~= self.current_anim then
		sprite.play_flipbook("#sprite", anim)
		self.current_anim = anim
	end

	self.dir = vmath.vector3()
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") and
	message.other_group == hash("House") then
		msg.post("main:/SceneParent#Main", "change_level")		
	end
end

function on_input(self, action_id, action)
	if action_id == hash("down") then
		self.dir.y = -1
	elseif action_id == hash("up") then
		self.dir.y = 1
	elseif action_id == hash("left") then
		self.dir.x = -1
	elseif action_id == hash("right") then
		self.dir.x = 1
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
