local speed = 300
local GameManager = require("_scripts.GameManager")
local current_level_name
local WINDOW_WIDTH = tonumber(sys.get_config("display.width"))
local WINDOW_HEIGHT = tonumber(sys.get_config("display.height"))

function init(self)
	msg.post(".", "acquire_input_focus")
	current_level_name = GameManager.get_current_level()
	self.dir = vmath.vector3()
	self.current_anim = nil
	pprint("height: ".. WINDOW_HEIGHT)
	pprint("width: " .. WINDOW_WIDTH)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	local move_dir = vmath.vector3(self.dir.x, self.dir.y, 0)
	if vmath.length_sqr(move_dir) > 0 then
		move_dir = vmath.normalize(move_dir)
	end

	local p = go.get_position()
	local new_p = p + move_dir * speed * dt

	local shape_props = physics.get_shape("#yeti_collisionobject", "yeti_hitbox")
	local margin_x = shape_props.dimensions.x / 2
	local margin_y = shape_props.dimensions.y / 2

	if new_p.x < margin_x then new_p.x = margin_x
	elseif new_p.x > (WINDOW_WIDTH - margin_x) then new_p.x = WINDOW_WIDTH - margin_x end

	if new_p.y < margin_y then new_p.y = margin_y
	elseif new_p.y > (WINDOW_HEIGHT - margin_y) then new_p.y = WINDOW_HEIGHT - margin_y end

	go.set_position(new_p)

	local anim = hash("front")
	if move_dir.x > 0 then anim = hash("right")
	elseif move_dir.x < 0 then anim = hash("left")
	elseif move_dir.y > 0 then anim = hash("back")
	elseif move_dir.y < 0 then anim = hash("front")
	end

	if anim ~= self.current_anim then
		sprite.play_flipbook("#sprite", anim)
		self.current_anim = anim
	end
end

local function update_direction(self, axis, value, is_pressed)
	if is_pressed then
		self.dir[axis] = value
	else
		if self.dir[axis] == value then
			self.dir[axis] = 0
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		print("Ho toccato qualcosa che appartiene al gruppo: " .. tostring(message.other_group))

		if message.other_group == hash("Game") then
			msg.post("main:/SceneParent#Main", "change_level", { target = "MiniGame" })
		elseif message.other_group == hash("School") then
			msg.post("main:/SceneParent#Main", "change_level", { target = "School" })
		end
	end

	if message_id == hash("move_up") then
		update_direction(self, "y", 1, message.pressed)
	elseif message_id == hash("move_down") then
		update_direction(self, "y", -1, message.pressed)
	elseif message_id == hash("move_left") then
		update_direction(self, "x", -1, message.pressed)
	elseif message_id == hash("move_right") then
		update_direction(self, "x", 1, message.pressed)
	end
end

function on_input(self, action_id, action)
	local used_input = false

	if action_id == hash("up") then
		update_direction(self, "y", 1, not action.released)
		used_input = true
	elseif action_id == hash("down") then
		update_direction(self, "y", -1, not action.released)
		used_input = true
	elseif action_id == hash("left") then
		update_direction(self, "x", -1, not action.released)
		used_input = true
	elseif action_id == hash("right") then
		update_direction(self, "x", 1, not action.released)
		used_input = true
	end

	return false 
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end