components {
  id: "freeMode"
  component: "/_scripts/Restaurant/yeti_restaurant.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"front\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/yeti.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "yeti_collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"player\"\n"
  "mask: \"environment\"\n"
  "mask: \"map\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -23.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"yeti_hitbox\"\n"
  "  }\n"
  "  data: 38.3046\n"
  "  data: 22.126608\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
