embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"rock_transparent\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/_restaurant/environment/environment.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "rockCollisionObject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"environment\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -1.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"rockHitbox\"\n"
  "  }\n"
  "  data: 16.820808\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
