embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"table_transparent\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/_restaurant/environment/environment.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "tableCollisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"table\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 6.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 23.563637\n"
  "  data: 13.613574\n"
  "  data: 9.6\n"
  "}\n"
  ""
}
