embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"tree_transparent\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/_restaurant/environment/environment.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "treeCollisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"environment\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -4.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"hitbox1\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 15.0\n"
  "      y: -9.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"hitbox2\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -15.0\n"
  "      y: -9.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "    id: \"hitbox3\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -25.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 9\n"
  "    count: 3\n"
  "    id: \"hitbox4\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 1.0\n"
  "      y: 17.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 12\n"
  "    count: 3\n"
  "    id: \"hitbox5\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 1.0\n"
  "      y: 23.0\n"
  "      z: 0.1\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 15\n"
  "    count: 3\n"
  "    id: \"hitbox6\"\n"
  "  }\n"
  "  data: 10.0\n"
  "  data: 17.330446\n"
  "  data: 10.0\n"
  "  data: 4.896085\n"
  "  data: 12.567485\n"
  "  data: 10.0\n"
  "  data: 4.896085\n"
  "  data: 12.567485\n"
  "  data: 10.0\n"
  "  data: 4.896085\n"
  "  data: 3.306518\n"
  "  data: 10.0\n"
  "  data: 6.574029\n"
  "  data: 3.306518\n"
  "  data: 10.0\n"
  "  data: 2.170648\n"
  "  data: 3.306518\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
