components {
  id: "obstacle"
  component: "/_scripts/MiniGame/element.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"rock\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/_miniGame/_obstacles/obstacles.atlas\"\n"
  "}\n"
  ""
  scale {
    x: 0.33
    y: 0.33
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"Rock\"\n"
  "mask: \"Player\"\n"
  "mask: \"Map\"\n"
  "mask: \"Tree\"\n"
  "mask: \"Coin\"\n"
  "mask: \"FinishLine\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 1.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"hit1\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -13.0\n"
  "      y: 1.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 13.0\n"
  "      y: 1.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "  }\n"
  "  data: 10.0\n"
  "  data: 5.75033\n"
  "  data: 10.0\n"
  "  data: 2.9056766\n"
  "  data: 3.389652\n"
  "  data: 10.0\n"
  "  data: 2.9056766\n"
  "  data: 3.389652\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
