components {
  id: "obstacle"
  component: "/_scripts/MiniGame/element.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"snowman\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/_miniGame/_obstacles/obstacles.atlas\"\n"
  "}\n"
  ""
  scale {
    x: 0.838952
    y: 0.838952
    z: 2.542278
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"Rock\"\n"
  "mask: \"Player\"\n"
  "mask: \"Map\"\n"
  "mask: \"Tree\"\n"
  "mask: \"Rock\"\n"
  "mask: \"Coin\"\n"
  "mask: \"KnowledgeItem\"\n"
  "mask: \"FinishLine\"\n"
  "mask: \"KnowledgePowerUp\"\n"
  "mask: \"CoinPowerUp\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 7.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"hit1\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -11.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"hit2\"\n"
  "  }\n"
  "  data: 8.049562\n"
  "  data: 7.741173\n"
  "  data: 11.56416\n"
  "  data: 11.3219595\n"
  "  data: 12.176438\n"
  "  data: 6.96768\n"
  "}\n"
  ""
}
